### ISSUE TITLE
Can you do spheres?

### ISSUE THREAD

**Issue by masonwheeler** [eranimo/hexgen#7]
Hexgen is beautiful!  It does everything I've been looking for for world generation, building detailed data about the world and exporting it to JSON, just like I need... except it puts it on a flat map.

Would it be possible to extend this concept to the generation of a spherical hex map (ie. the subdivided icosahedron "sphere")?

**Comment by eranimo** [comment]
Thanks for the interest, but this project has been replaced with [TerraNova](https://github.com/eranimo/terranova) (a browser-based Typescript rewrite).

Both Hexgen and TerraNova operate on simple 2D grids, not representations of spheres. Hexgen could be represented as a icosahedron by changing the renderer, you're welcome to fork it and try.

**Comment by masonwheeler** [comment]
Unfortunately it's not as simple as changing the renderer; on a sphere world there's a lot more horizontal space at the equator than at the poles, so it would require throwing away or compressing/merging a bunch of data.

**Comment by eranimo** [comment]
@masonwheeler I have a new project that uses spheres! https://github.com/eranimo/terra
